id: P14E449C2
initial_creation_type: ocr
source_metadata:
  volumes:
    2b35725d587f405197d8fe2b7b7e43a1:
      base_file: v013.txt
      image_group_id: I1PD95858
      title: ཡེ་ཤེས་དབང་ཕྱུག་མའི་སྒྲུབ་ཐབས།
      total_pages: 2043
      volume_number: 13
